version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: dockerfile
    ports:
      - '3000:3000'
    restart: always
    environment:
      - MONGODB_URI=mongodb://mongo:27017/crud_user
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules  
  mongo:
    image: mongo
    ports:
      - '27017:27017'
  